%YAML:1.0
image_width: 640
image_height: 480
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 558.59301 , 0., 319.72807, 0.,
        558.94200,  223.19173, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [  0.01089,   0.06490,   -0.00386,   -0.00162,  0.00000 ]